require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  
AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/**"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
